graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false

    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: false
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION


server:
  http2:
    enabled: true